// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/tool.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolService_GetTools_FullMethodName      = "/tool.ToolService/GetTools"
	ToolService_GetTool_FullMethodName       = "/tool.ToolService/GetTool"
	ToolService_GetCategories_FullMethodName = "/tool.ToolService/GetCategories"
	ToolService_SearchTools_FullMethodName   = "/tool.ToolService/SearchTools"
	ToolService_GetToolDetail_FullMethodName = "/tool.ToolService/GetToolDetail"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 工具服务
type ToolServiceClient interface {
	// 获取工具列表
	GetTools(ctx context.Context, in *GetToolsRequest, opts ...grpc.CallOption) (*GetToolsResponse, error)
	// 获取单个工具
	GetTool(ctx context.Context, in *GetToolRequest, opts ...grpc.CallOption) (*Tool, error)
	// 获取分类列表
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	// 搜索工具
	SearchTools(ctx context.Context, in *SearchToolsRequest, opts ...grpc.CallOption) (*SearchToolsResponse, error)
	// 获取工具详情
	GetToolDetail(ctx context.Context, in *GetToolDetailRequest, opts ...grpc.CallOption) (*GetToolDetailResponse, error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) GetTools(ctx context.Context, in *GetToolsRequest, opts ...grpc.CallOption) (*GetToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolsResponse)
	err := c.cc.Invoke(ctx, ToolService_GetTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetTool(ctx context.Context, in *GetToolRequest, opts ...grpc.CallOption) (*Tool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tool)
	err := c.cc.Invoke(ctx, ToolService_GetTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, ToolService_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) SearchTools(ctx context.Context, in *SearchToolsRequest, opts ...grpc.CallOption) (*SearchToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchToolsResponse)
	err := c.cc.Invoke(ctx, ToolService_SearchTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolServiceClient) GetToolDetail(ctx context.Context, in *GetToolDetailRequest, opts ...grpc.CallOption) (*GetToolDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolDetailResponse)
	err := c.cc.Invoke(ctx, ToolService_GetToolDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
//
// 工具服务
type ToolServiceServer interface {
	// 获取工具列表
	GetTools(context.Context, *GetToolsRequest) (*GetToolsResponse, error)
	// 获取单个工具
	GetTool(context.Context, *GetToolRequest) (*Tool, error)
	// 获取分类列表
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	// 搜索工具
	SearchTools(context.Context, *SearchToolsRequest) (*SearchToolsResponse, error)
	// 获取工具详情
	GetToolDetail(context.Context, *GetToolDetailRequest) (*GetToolDetailResponse, error)
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) GetTools(context.Context, *GetToolsRequest) (*GetToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTools not implemented")
}
func (UnimplementedToolServiceServer) GetTool(context.Context, *GetToolRequest) (*Tool, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTool not implemented")
}
func (UnimplementedToolServiceServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedToolServiceServer) SearchTools(context.Context, *SearchToolsRequest) (*SearchToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTools not implemented")
}
func (UnimplementedToolServiceServer) GetToolDetail(context.Context, *GetToolDetailRequest) (*GetToolDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolDetail not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_GetTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetTools(ctx, req.(*GetToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetTool(ctx, req.(*GetToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_SearchTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).SearchTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_SearchTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).SearchTools(ctx, req.(*SearchToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolService_GetToolDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolServiceServer).GetToolDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolService_GetToolDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolServiceServer).GetToolDetail(ctx, req.(*GetToolDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tool.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTools",
			Handler:    _ToolService_GetTools_Handler,
		},
		{
			MethodName: "GetTool",
			Handler:    _ToolService_GetTool_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _ToolService_GetCategories_Handler,
		},
		{
			MethodName: "SearchTools",
			Handler:    _ToolService_SearchTools_Handler,
		},
		{
			MethodName: "GetToolDetail",
			Handler:    _ToolService_GetToolDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tool.proto",
}
